---

- include: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family|lower }}.yml"
      - paths:
      - ../vars


- name: Install Kerberos and LDAP clients
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ kerb_packages }}"

- name: Configure Kerberos integration with AD
  template: src={{ krb5.conf }} dest={{ krb_conf_path }}
            owner=root group=root mode=0644

- name: Install Samba
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ samba_packages }}"

- name: Configure Samba as a domain member
  template: src={{ smb_conf }} dest={{ smb_conf_path }}
            owner=root group=root mode=0644
  notify: restart samba

- name: Ensure Samba is started and enabled on boot
  service: name=smb state=started enabled=yes

- name: Join AD with Samba to generate the keytab
  command: net ads join createcomputer={{ adauth_server_ou }} -U "{{ adauth_username }}"%"{{ adauth_password }}"
  args:
    creates: /etc/krb5.keytab

- name: Get kerberos ticket with the sambe keytab
  command: kinit -k -t /etc/krb5.keytab {{ ansible_hostname | upper }}$\@{{ adauth_realm }}
  args:
    creates: /tmp/krb5cc_0

- name: Install SSSD and related
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ sssd_packages }}"

- name: Configure SSSD to use AD for authentication
  template: src={{ sssd_conf }} dest={{ sssd_conf_path }}
            owner=root group=root mode=0600

- name: Ensure SSSD is started and enabled on boot
  service: name=sssd state=started enabled=yes

- include: freebsd.yml
  when: ansible_os_family == 'FreeBSD'
  tags: package

- include: centos.yml
  when: ansible_os_family == 'CentOS'
  tags: package

  #- include: debian.yml
  #  when: ansible_os_family == 'Debian'
  #  tags: package
  #
  #- include: ubuntu.yml
  #  when: ansible_os_family == 'Ubuntu'
  #  tags: package

- include: freebsd.yml
  when: ansible_os_family == 'FreeBSD'
  tags: package


- include: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family|lower }}.yml"
      - paths:
      - ../vars
