---
- name: Apply the ifcfg template
  template:
    src: templates/ifcfg
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"

- name: Apply the resolv.conf template
  template:
    src: templates/resolv.conf
    dest: /etc/resolv.conf

- name: Apply the hosts template
  template:
    src: templates/hosts
    dest: /etc/hosts
    
#- name: Restart network WARN This will break connection
#  service:
#      name: network
#      state: restarted
#  async: 2
#  poll: 0

