# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "ubuntu/trusty64"
      ubuntu.vm.network "private_network", ip: "192.168.33.10"
      ubuntu.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "test.yml"
      end
  end
  config.vm.define "centos" do |centos|
      centos.vm.box = "centos/7"
      centos.vm.network "private_network", ip: "192.168.33.20"
      centos.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "test.yml"
      end
  end
end
