####################################################################
#  Join Windows client to domain
####################################################################
- name: Join windows host to {{ ad_domain_name }} domain
  win_domain_membership:
    dns_domain_name: '{{ ad_domain_name }}'
    hostname: '{{ ansible_hostname }}'
    domain_admin_user: 'administrator@{{ ad_domain_name }}'
    domain_admin_password: '{{ ad_safe_mode_password }}'
    state: domain
  register: domain_state

- win_reboot:
  when: domain_state.reboot_required
