---
adauth_workgroup: "ISTS"
adauth_realm: "ists"
adauth_pdc: "team{{ machines[inventory_hostname]['team_id'] }}.ists"
adauth_pdc_ip: "{{ machines[inventory_hostname]['ip'] }}"
adauth_sdc: "team{{ machines[inventory_hostname]['team_id'] }}.ists"
adauth_sdc_ip: "{{ machines[inventory_hostname]['ip'] }}"
adauth_ldap_base: "DC=ists"
adauth_username: "administrator"
adauth_password: "Changeme-2018"
adauth_server_ou: ""
adauth_access_filter: "(&(objectClass=user)(memberOf=CN=UnixServers,OU=UnixServers,DC=ists))"
#adauth_access_filter: "(&(objectClass=user)(|(memberOf=CN=OSunix,OU=UnixServers,DC=example,DC=com)(memberOf=CN=DBAunix,OU=UnixServers,DC=example,DC=com)))"
#adauth_access_filter: "(&(objectClass=user)(|(sAMAccountName=john)(sAMAccountName=merry)))"

