# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "vsrx" do |vsrx|
      vsrx.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
      vsrx.vm.network "private_network", ip: "192.168.33.100", nic_type: 'virtio'
      vsrx.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "test.yml"
      end
  end
end
